services:
  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG-}
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:5.2.0@sha256:c04d44b431d4035fc5ddb2f6e8f342a8389327a8625ff834b824ffe86af62097
    environment:
      - AWS_REGION=ap-southeast-1
      - DYNAMO_ENDPOINT=http://localstack:4566
    ports:
      - 8001:8001
