[tool.poetry]
name = "radiojournal-scripts"
version = "0.1.6"
description = "Scripts for radiojournal"
authors = ["Thitat Auareesuksakul <flux@thitat.net>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.5"
aiodynamo = {version = "24.7", extras = ["httpx"]}
yarl = "1.9.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
