[tool.poetry]
name = "radiojournal-scripts"
version = "0.2.0"
description = "Scripts for radiojournal"
authors = ["Thitat Auareesuksakul <flux@thitat.net>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.13.0"
aiodynamo = {version = "24.7", extras = ["httpx"]}
yarl = "1.17.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
