name: Build radiojournal frontend

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          package_json_file: frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install PNPM dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build radiojournal frontend
        working-directory: frontend
        run: pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          name: frontend
          path: frontend/build
          include-hidden-files: true
          retention-days: 3
