name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "The bump type for new release"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - version
      version:
        type: string
        description: "Explicit version to bump to, if `bump-type` is set to `version`"

jobs:
  bump-version:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      # renovate: datasource=github-releases depName=python-poetry/poetry
      POETRY_VERSION: "2.4.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install poetry
        run: pip3 install "poetry==${{ env.POETRY_VERSION }}"

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ".python-version"
          cache: "poetry"

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install rust toolchain
        run: cargo version

      - name: Bump packages to new version number
        env:
          BUMP_TYPE: ${{ inputs.bump-type }}
          VERSION: ${{ inputs.version }}
        run: ./scripts/bump_version.sh "$BUMP_TYPE" "$VERSION"

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "release: ${{ env.NEXT_VERSION }}"
          title: "release: ${{ env.NEXT_VERSION }}"
          body: "Bump radiojournal packages to version ${{ env.NEXT_VERSION }}"
          branch: release-${{ env.NEXT_VERSION }}
          reviewers: |
            fluxth
