name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'The bump type for new release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - version
      version:
        type: string
        description:
          'Explicit version to bump to, if `bump-type` is set to `version`'

jobs:
  bump-version:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      # renovate: datasource=github-releases depName=python-poetry/poetry
      POETRY_VERSION: '2.3.4'
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install poetry
        run: pip3 install "poetry==${{ env.POETRY_VERSION }}"

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          package_json_file: frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install rust toolchain
        run: cargo version

      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: tests
          save-if: false

      - name: Bump packages to new version number
        env:
          BUMP_TYPE: ${{ inputs.bump-type }}
          VERSION: ${{ inputs.version }}
        run: ./scripts/bump_version.sh "$BUMP_TYPE" "$VERSION"

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: 'release: ${{ env.NEXT_VERSION }}'
          title: 'release: ${{ env.NEXT_VERSION }}'
          body: 'Bump radiojournal packages to version ${{ env.NEXT_VERSION }}'
          branch: release-${{ env.NEXT_VERSION }}
          reviewers: |
            fluxth
