name: Lint and test radiojournal codebase

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # renovate: datasource=github-releases depName=terraform-linters/tflint
      TFLINT_VERSION: 'v0.61.0'
      # renovate: datasource=github-releases depName=hashicorp/terraform
      TERRAFORM_VERSION: 'v1.14.7'
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        name: Cache tflint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        name: Setup tflint
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Initialize tflint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          package_json_file: frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install PNPM dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Install rust toolchain
        run: cargo version

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  test-rust:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install rust toolchain
        run: cargo version

      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: tests
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Test rust code
        run: cargo test
