name: Test radiojournal codebase

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache rustup directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.rustup
          key: rustup-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            rustup-${{ runner.os }}-

      - name: Cache cargo registry
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/registry
          key: cargo-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Cache cargo target directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            target
            !target/lambda
          key: cargo-target-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

      - name: Test rust code
        run: cargo test
